name: "Test-falilure"
on:
  pull_request:
    branches: ["main"]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking out repo"
        uses: actions/checkout@v4

      - name: "Installing dependencies"
        run: "npm install"

      - name: "Linting"
        id: lint
        continue-on-error: true
        run: "npm run lint"
        

      - name: "Checking if error"
        if: steps.lint.outcome != 'success'
        run: exit 1
